<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.4.0</Version>
    <Description>F# serialization library for the Apache Parquet file format. Built on top of Parquet.Net, and with first-class support for F# types such as records, options, lists and discriminated unions.</Description>
    <Authors>Rob Earwaker</Authors>
    <Company />
    <RepositoryUrl>https://github.com/rob-earwaker/parquet-fsharp</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright © Rob Earwaker 2025</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <Compile Include="Schema.fs" />
    <Compile Include="Expression.fs" />
    <Compile Include="TypeInfo.fs" />
    <Compile Include="TypeDefinitions.fs" />
    <Compile Include="Settings.fs" />
    <Compile Include="Converter.fs" />
    <Compile Include="Converters\BoolConverter.fs" />
    <Compile Include="Converters\Int8Converter.fs" />
    <Compile Include="Converters\Int16Converter.fs" />
    <Compile Include="Converters\Int32Converter.fs" />
    <Compile Include="Converters\Int64Converter.fs" />
    <Compile Include="Converters\UInt8Converter.fs" />
    <Compile Include="Converters\UInt16Converter.fs" />
    <Compile Include="Converters\UInt32Converter.fs" />
    <Compile Include="Converters\UInt64Converter.fs" />
    <Compile Include="Converters\Float32Converter.fs" />
    <Compile Include="Converters\Float64Converter.fs" />
    <Compile Include="Converters\DecimalConverter.fs" />
    <Compile Include="Converters\GuidConverter.fs" />
    <Compile Include="Converters\EnumConverter.fs" />
    <Compile Include="Converters\TimeSpanConverter.fs" />
    <Compile Include="Converters\DateTimeConverter.fs" />
    <Compile Include="Converters\DateTimeOffsetConverter.fs" />
    <Compile Include="Converters\StringConverter.fs" />
    <Compile Include="Converters\ByteArrayConverter.fs" />
    <Compile Include="Converters\ListConverter.fs" />
    <Compile Include="Converters\Array1dConverter.fs" />
    <Compile Include="Converters\ResizeArrayConverter.fs" />
    <Compile Include="Converters\RecordConverter.fs" />
    <Compile Include="Converters\UnionConverter.fs" />
    <Compile Include="Converters\OptionConverter.fs" />
    <Compile Include="Converters\ValueOptionConverter.fs" />
    <Compile Include="Converters\NullableConverter.fs" />
    <Compile Include="Attributes.fs" />
    <Compile Include="Shredder.fs" />
    <Compile Include="Assembler.fs" />
    <Compile Include="ParquetSerializer.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Parquet.Net" Version="5.6.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.300" />
  </ItemGroup>

</Project>
