<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.4.0</Version>
    <Description>F# serialization library for the Apache Parquet file format. Built on top of Parquet.Net, and with first-class support for F# types such as records, options, lists and discriminated unions.</Description>
    <Authors>Rob Earwaker</Authors>
    <Company />
    <RepositoryUrl>https://github.com/rob-earwaker/parquet-fsharp</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright © Rob Earwaker 2025</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <Compile Include="Schema.fs" />
    <Compile Include="Expression.fs" />
    <Compile Include="TypeInfo.fs" />
    <Compile Include="TypeDefinitions.fs" />
    <Compile Include="Settings.fs" />
    <Compile Include="Converter.fs" />
    <Compile Include="Converters\DefaultBoolConverter.fs" />
    <Compile Include="Converters\DefaultInt8Converter.fs" />
    <Compile Include="Converters\DefaultInt16Converter.fs" />
    <Compile Include="Converters\DefaultInt32Converter.fs" />
    <Compile Include="Converters\DefaultInt64Converter.fs" />
    <Compile Include="Converters\DefaultUInt8Converter.fs" />
    <Compile Include="Converters\DefaultUInt16Converter.fs" />
    <Compile Include="Converters\DefaultUInt32Converter.fs" />
    <Compile Include="Converters\DefaultUInt64Converter.fs" />
    <Compile Include="Converters\DefaultFloat32Converter.fs" />
    <Compile Include="Converters\DefaultFloat64Converter.fs" />
    <Compile Include="Converters\DefaultDecimalConverter.fs" />
    <Compile Include="Converters\DefaultGuidConverter.fs" />
    <Compile Include="Converters\DefaultEnumConverter.fs" />
    <Compile Include="Converters\DefaultTimeSpanConverter.fs" />
    <Compile Include="Converters\DefaultDateTimeConverter.fs" />
    <Compile Include="Converters\DefaultDateTimeOffsetConverter.fs" />
    <Compile Include="Converters\DefaultStringConverter.fs" />
    <Compile Include="Converters\DefaultByteArrayConverter.fs" />
    <Compile Include="Converters\DefaultListConverter.fs" />
    <Compile Include="Converters\DefaultArray1dConverter.fs" />
    <Compile Include="Converters\DefaultResizeArrayConverter.fs" />
    <Compile Include="Converters\DefaultRecordConverter.fs" />
    <Compile Include="Converters\DefaultUnionConverter.fs" />
    <Compile Include="Converters\DefaultOptionConverter.fs" />
    <Compile Include="Converters\DefaultValueOptionConverter.fs" />
    <Compile Include="Converters\DefaultNullableConverter.fs" />
    <Compile Include="Shredder.fs" />
    <Compile Include="Assembler.fs" />
    <Compile Include="ParquetSerializer.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Parquet.Net" Version="5.6.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.300" />
  </ItemGroup>

</Project>
